import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import localFont from 'next/font/local'

const iransans = localFont({
  src: [
    {
      path: './fonts/IranSansRegular.ttf',
      weight: '100 500',
      style: 'normal',
    },
    {
      path: './fonts/IranSansBold.ttf',
      weight: '600 900',
      style: 'normal',
    },
  ],
  display: "swap",
  fallback: ["system-ui", "arial"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`antialiased ${iransans.className}`}
      >
          {children}
      </body>
    </html>
  );
}
